name: filepicker_windows
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  win32:
    git:
      git@github.com:timsneath/win32.git
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # plugin:
  #   platforms:
  #     windows: